"""
Quantitative Research Platform

A professional quantitative research environment for trading strategies.
"""

# Import all modules
from research_platform.notebook import (
    ResearchWorkspace,
    ResearchWorkspaceManager,
    NotebookCell,
    CellType,
    Hypothesis,
    HypothesisStatus,
    Observation,
    Conclusion,
    DatasetAttachment,
    Visualization,
)
from research_platform.datasets import (
    DatasetManager,
    Dataset,
    DatasetMetadata,
    DatasetVersion,
    DataSchema,
    DataStatistics,
    DataQualityReport,
    DataLineage,
    DataLineageNode,
    DataType,
    DatasetStatus,
    ValidationLevel,
)
from research_platform.feature_store import (
    FeatureStore,
    StoredFeature,
    FeatureVersion,
    FeatureDependency,
    FeatureGroup,
    FeatureTest,
    FeatureType,
    FeatureCategory,
    FeatureStatus,
)
from research_platform.experiments import (
    ExperimentManager,
    Experiment,
    ExperimentResult,
    ExecutionRecord,
    ParameterSpec,
    ParameterSet,
    MetricValue,
    MetricSummary,
    ExperimentType,
    ExperimentStatus,
    MetricType,
)
from research_platform.models import (
    ModelRegistry,
    RegisteredModel,
    ModelVersion,
    DeploymentRecord,
    ApprovalWorkflow,
    ApprovalStep,
    ApprovalAction,
    ModelType,
    ModelStatus,
)
from research_platform.benchmarks import (
    BenchmarkLibrary,
    Benchmark,
    BenchmarkResult,
    BenchmarkMetrics,
    BenchmarkPeriod,
    BenchmarkType,
    BenchmarkStatus,
)
from research_platform.validation import (
    ValidationCenter,
    ValidationSuite,
    ValidationResult,
    ValidationWindow,
    MonteCarloResult,
    SensitivityResult,
    StabilityResult,
    ValidationType,
    ValidationStatus,
)
from research_platform.analytics import (
    PerformanceAnalytics,
    EquityCurve,
    EquityPoint,
    RollingWindow,
    DrawdownAnalysis,
    TradeStatistics,
    RiskMetrics,
    ConfidenceCalibration,
    DecisionQualityMetrics,
    MetricType as AnalyticsMetricType,
)
from research_platform.explainability import (
    ModelExplainability,
    FeatureImportance,
    PermutationResult,
    LocalExplanation,
    FeatureContribution,
    GlobalExplanation,
    FeatureInteraction,
    UncertaintyEstimate,
    ExplanationType,
    UncertaintyType,
)
from research_platform.decision_replay import (
    DecisionReplayEngine,
    TradeReplay,
    DecisionSnapshot,
    AvailableInformation,
    ModelOutput,
    RiskEvaluation,
    AIReasoning,
    ExecutionDecision,
    DecisionType,
    DecisionOutcome,
    ReplayStatus,
)
from research_platform.automation import (
    NightlyPipeline,
    PipelineRun,
    PipelineTask,
    DeploymentRecommendation,
    PipelineStage,
    PipelineStatus,
    TaskStatus,
)

__all__ = [
    # Notebook
    "ResearchWorkspace",
    "ResearchWorkspaceManager",
    "NotebookCell",
    "CellType",
    "Hypothesis",
    "HypothesisStatus",
    "Observation",
    "Conclusion",
    "DatasetAttachment",
    "Visualization",
    # Datasets
    "DatasetManager",
    "Dataset",
    "DatasetMetadata",
    "DatasetVersion",
    "DataSchema",
    "DataStatistics",
    "DataQualityReport",
    "DataLineage",
    "DataLineageNode",
    "DataType",
    "DatasetStatus",
    "ValidationLevel",
    # Feature Store
    "FeatureStore",
    "StoredFeature",
    "FeatureVersion",
    "FeatureDependency",
    "FeatureGroup",
    "FeatureTest",
    "FeatureType",
    "FeatureCategory",
    "FeatureStatus",
    # Experiments
    "ExperimentManager",
    "Experiment",
    "ExperimentResult",
    "ExecutionRecord",
    "ParameterSpec",
    "ParameterSet",
    "MetricValue",
    "MetricSummary",
    "ExperimentType",
    "ExperimentStatus",
    "MetricType",
    # Models
    "ModelRegistry",
    "RegisteredModel",
    "ModelVersion",
    "DeploymentRecord",
    "ApprovalWorkflow",
    "ApprovalStep",
    "ApprovalAction",
    "ModelType",
    "ModelStatus",
    # Benchmarks
    "BenchmarkLibrary",
    "Benchmark",
    "BenchmarkResult",
    "BenchmarkMetrics",
    "BenchmarkPeriod",
    "BenchmarkType",
    "BenchmarkStatus",
    # Validation
    "ValidationCenter",
    "ValidationSuite",
    "ValidationResult",
    "ValidationWindow",
    "MonteCarloResult",
    "SensitivityResult",
    "StabilityResult",
    "ValidationType",
    "ValidationStatus",
    # Analytics
    "PerformanceAnalytics",
    "EquityCurve",
    "EquityPoint",
    "RollingWindow",
    "DrawdownAnalysis",
    "TradeStatistics",
    "RiskMetrics",
    "ConfidenceCalibration",
    "DecisionQualityMetrics",
    "AnalyticsMetricType",
    # Explainability
    "ModelExplainability",
    "FeatureImportance",
    "PermutationResult",
    "LocalExplanation",
    "FeatureContribution",
    "GlobalExplanation",
    "FeatureInteraction",
    "UncertaintyEstimate",
    "ExplanationType",
    "UncertaintyType",
    # Decision Replay
    "DecisionReplayEngine",
    "TradeReplay",
    "DecisionSnapshot",
    "AvailableInformation",
    "ModelOutput",
    "RiskEvaluation",
    "AIReasoning",
    "ExecutionDecision",
    "DecisionType",
    "DecisionOutcome",
    "ReplayStatus",
    # Automation
    "NightlyPipeline",
    "PipelineRun",
    "PipelineTask",
    "DeploymentRecommendation",
    "PipelineStage",
    "PipelineStatus",
    "TaskStatus",
]
