"""
Strategy Plugin Base Class and Data Models

Defines the standard lifecycle interface and data structures for all trading strategy plugins.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple
from uuid import UUID, uuid4


class PluginState(Enum):
    """Plugin lifecycle states"""
    UNLOADED = "unloaded"
    LOADING = "loading"
    INITIALIZED = "initialized"
    RUNNING = "running"
    PAUSED = "paused"
    STOPPED = "stopped"
    ERROR = "error"
    UNLOADING = "unloading"


@dataclass
class PluginMetadata:
    """Plugin metadata and identification"""
    id: str
    name: str
    version: str
    author: str
    description: str
    tags: List[str] = field(default_factory=list)
    supported_markets: List[str] = field(default_factory=list)
    min_confidence: float = 60.0
    max_drawdown_tolerance: float = 20.0
    requires_market_data: bool = True
    requires_ml: bool = False
    home_url: Optional[str] = None
    license: str = "MIT"
    api_version: str = "1.0"
    dependencies: List[str] = field(default_factory=list)
    created_at: datetime = field(default_factory=datetime.utcnow)
    updated_at: datetime = field(default_factory=datetime.utcnow)
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "name": self.name,
            "version": self.version,
            "author": self.author,
            "description": self.description,
            "tags": self.tags,
            "supported_markets": self.supported_markets,
            "min_confidence": self.min_confidence,
            "max_drawdown_tolerance": self.max_drawdown_tolerance,
            "requires_market_data": self.requires_market_data,
            "requires_ml": self.requires_ml,
            "home_url": self.home_url,
            "license": self.license,
            "api_version": self.api_version,
            "dependencies": self.dependencies,
            "created_at": self.created_at.isoformat(),
            "updated_at": self.updated_at.isoformat(),
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "PluginMetadata":
        data = data.copy()
        if "created_at" in data and isinstance(data["created_at"], str):
            data["created_at"] = datetime.fromisoformat(data["created_at"])
        if "updated_at" in data and isinstance(data["updated_at"], str):
            data["updated_at"] = datetime.fromisoformat(data["updated_at"])
        return cls(**data)


@dataclass
class TickData:
    """Standardized tick data for strategy consumption"""
    symbol: str
    price: float
    timestamp: datetime = field(default_factory=datetime.utcnow)
    bid: Optional[float] = None
    ask: Optional[float] = None
    volume: Optional[float] = None
    tick_id: Optional[str] = None
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "TickData":
        timestamp = data.get("timestamp")
        if isinstance(timestamp, str):
            timestamp = datetime.fromisoformat(timestamp)
        elif timestamp is None:
            timestamp = datetime.utcnow()
        return cls(
            symbol=data.get("symbol", ""),
            price=float(data.get("price", data.get("quote", 0))),
            timestamp=timestamp,
            bid=data.get("bid"),
            ask=data.get("ask"),
            volume=data.get("volume"),
            tick_id=data.get("tick_id"),
        )
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "symbol": self.symbol,
            "price": self.price,
            "timestamp": self.timestamp.isoformat(),
            "bid": self.bid,
            "ask": self.ask,
            "volume": self.volume,
            "tick_id": self.tick_id,
        }


@dataclass 
class Signal:
    """Trading signal generated by a strategy"""
    id: str = field(default_factory=lambda: str(uuid4()))
    plugin_id: str = ""
    plugin_name: str = ""
    direction: str = ""  # "CALL" (RISE) or "PUT" (FALL)
    confidence: float = 0.0
    reason: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=datetime.utcnow)
    price: float = 0.0
    market: str = ""
    valid_until: Optional[datetime] = None
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "plugin_id": self.plugin_id,
            "plugin_name": self.plugin_name,
            "direction": self.direction,
            "confidence": self.confidence,
            "reason": self.reason,
            "metadata": self.metadata,
            "timestamp": self.timestamp.isoformat(),
            "price": self.price,
            "market": self.market,
            "valid_until": self.valid_until.isoformat() if self.valid_until else None,
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Signal":
        data = data.copy()
        if "timestamp" in data and isinstance(data["timestamp"], str):
            data["timestamp"] = datetime.fromisoformat(data["timestamp"])
        if "valid_until" in data and data["valid_until"]:
            data["valid_until"] = datetime.fromisoformat(data["valid_until"])
        return cls(**data)


@dataclass
class RiskValidation:
    """Risk validation result from a strategy"""
    plugin_id: str
    is_valid: bool
    approved_amount: float
    max_amount: float
    risk_score: float = 0.0
    warnings: List[str] = field(default_factory=list)
    errors: List[str] = field(default_factory=list)
    timestamp: datetime = field(default_factory=datetime.utcnow)
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "plugin_id": self.plugin_id,
            "is_valid": self.is_valid,
            "approved_amount": self.approved_amount,
            "max_amount": self.max_amount,
            "risk_score": self.risk_score,
            "warnings": self.warnings,
            "errors": self.errors,
            "timestamp": self.timestamp.isoformat(),
        }


@dataclass
class PerformanceMetrics:
    """Plugin performance tracking"""
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    total_profit: float = 0.0
    total_loss: float = 0.0
    max_drawdown: float = 0.0
    current_drawdown: float = 0.0
    avg_win: float = 0.0
    avg_loss: float = 0.0
    largest_win: float = 0.0
    largest_loss: float = 0.0
    win_rate: float = 0.0
    profit_factor: float = 0.0
    sharpe_ratio: float = 0.0
    last_updated: datetime = field(default_factory=datetime.utcnow)
    
    @property
    def net_profit(self) -> float:
        return self.total_profit + self.total_loss
    
    @property
    def expectancy(self) -> float:
        if self.total_trades == 0:
            return 0.0
        return self.net_profit / self.total_trades
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "total_trades": self.total_trades,
            "winning_trades": self.winning_trades,
            "losing_trades": self.losing_trades,
            "total_profit": self.total_profit,
            "total_loss": self.total_loss,
            "net_profit": self.net_profit,
            "max_drawdown": self.max_drawdown,
            "current_drawdown": self.current_drawdown,
            "avg_win": self.avg_win,
            "avg_loss": self.avg_loss,
            "largest_win": self.largest_win,
            "largest_loss": self.largest_loss,
            "win_rate": self.win_rate,
            "profit_factor": self.profit_factor,
            "sharpe_ratio": self.sharpe_ratio,
            "expectancy": self.expectancy,
            "last_updated": self.last_updated.isoformat(),
        }
    
    def record_trade(self, profit: float):
        """Record a completed trade"""
        self.total_trades += 1
        if profit > 0:
            self.winning_trades += 1
            self.total_profit += profit
            if profit > self.largest_win:
                self.largest_win = profit
        else:
            self.losing_trades += 1
            self.total_loss += profit
            if profit < self.largest_loss:
                self.largest_loss = profit
        
        # Update derived metrics
        if self.total_trades > 0:
            self.win_rate = (self.winning_trades / self.total_trades) * 100
        if self.total_profit > 0 and self.total_loss != 0:
            self.profit_factor = abs(self.total_profit / self.total_loss)
        if self.avg_win > 0 and self.avg_loss != 0:
            self.avg_win = self.total_profit / max(self.winning_trades, 1)
            self.avg_loss = abs(self.total_loss) / max(self.losing_trades, 1)
        
        self.last_updated = datetime.utcnow()


class StrategyPlugin(ABC):
    """
    Abstract base class for all trading strategy plugins.
    
    All strategy plugins must implement the standard lifecycle methods:
    - initialize(): Called when the plugin is loaded
    - on_tick(): Called for each market tick
    - generate_signal(): Generate a trading signal
    - validate_risk(): Validate signal against risk rules
    - cleanup(): Called when the plugin is unloaded
    
    The plugin system ensures:
    - Isolated execution environment per plugin
    - Standardized signal and risk validation interfaces
    - Hot-reload capability without system restart
    - Version management and compatibility checks
    """
    
    def __init__(self):
        self._metadata: Optional[PluginMetadata] = None
        self._state: PluginState = PluginState.UNLOADED
        self._metrics = PerformanceMetrics()
        self._config: Dict[str, Any] = {}
        self._initialized = False
        self._error: Optional[str] = None
    
    @property
    @abstractmethod
    def metadata(self) -> PluginMetadata:
        """Return plugin metadata"""
        pass
    
    @property
    def state(self) -> PluginState:
        return self._state
    
    @property
    def metrics(self) -> PerformanceMetrics:
        return self._metrics
    
    @property
    def config(self) -> Dict[str, Any]:
        return self._config
    
    @property
    def is_initialized(self) -> bool:
        return self._initialized
    
    @property
    def error(self) -> Optional[str]:
        return self._error
    
    def configure(self, config: Dict[str, Any]) -> None:
        """Configure the plugin with settings"""
        self._config = config
        self._apply_config()
    
    def _apply_config(self) -> None:
        """Apply configuration - override in subclass if needed"""
        pass
    
    @abstractmethod
    async def initialize(self) -> bool:
        """
        Initialize the plugin.
        
        Called once when the plugin is loaded. Should:
        - Setup any required resources
        - Load saved state if available
        - Connect to external services
        - Return True if initialization successful
        
        Returns:
            bool: True if initialization successful, False otherwise
        """
        pass
    
    @abstractmethod
    async def on_tick(self, tick: TickData) -> None:
        """
        Process incoming market tick data.
        
        Called for each market price update. Plugins should:
        - Update internal price history
        - Run any continuous analysis
        - Update internal state
        
        Args:
            tick: TickData containing current market price
        """
        pass
    
    @abstractmethod
    async def generate_signal(self, tick: TickData) -> Optional[Signal]:
        """
        Generate a trading signal based on current market state.
        
        Called after on_tick when the strategy decides to generate a signal.
        Should return None if no signal is generated.
        
        Args:
            tick: Current tick data
            
        Returns:
            Optional[Signal]: Trading signal or None if no signal
        """
        pass
    
    @abstractmethod
    async def validate_risk(self, signal: Signal, account_balance: float) -> RiskValidation:
        """
        Validate a signal against risk rules.
        
        Called before executing a signal. Should validate:
        - Signal parameters against risk limits
        - Position sizing constraints
        - Account balance adequacy
        
        Args:
            signal: Signal to validate
            account_balance: Current account balance
            
        Returns:
            RiskValidation: Validation result with approved amount
        """
        pass
    
    @abstractmethod
    async def cleanup(self) -> None:
        """
        Cleanup resources when plugin is unloaded.
        
        Should:
        - Close any open connections
        - Save state
        - Release resources
        - Log final metrics
        """
        pass
    
    def on_trade_result(self, signal: Signal, profit: float, is_win: bool) -> None:
        """
        Called with the result of a trade executed from this signal.
        
        Override to update strategy-specific performance tracking.
        
        Args:
            signal: The signal that was traded
            profit: Trade profit/loss amount
            is_win: Whether the trade was a winner
        """
        self._metrics.record_trade(profit)
    
    def get_state(self) -> Dict[str, Any]:
        """Get current plugin state for persistence"""
        return {
            "state": self._state.value,
            "config": self._config,
            "metrics": self._metrics.to_dict(),
            "error": self._error,
        }
    
    def pause(self) -> None:
        """Pause the plugin"""
        if self._state == PluginState.RUNNING:
            self._state = PluginState.PAUSED
    
    def resume(self) -> None:
        """Resume the plugin"""
        if self._state == PluginState.PAUSED:
            self._state = PluginState.RUNNING
    
    def _set_state(self, state: PluginState) -> None:
        """Internal state setter"""
        self._state = state
    
    def _set_error(self, error: Optional[str]) -> None:
        """Internal error setter"""
        self._error = error
    
    def __repr__(self) -> str:
        return f"<{self.__class__.__name__} id={self._metadata.id if self._metadata else 'N/A'} state={self._state.value}>"
